[package]
name = "RemoteKeyboard"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.16", features = ["derive"] }
enigo = { version = "0.1.2" }
winit = "0.28.6"
